.\" # Copyright 2024 David Robillard <d@drobilla.net>
.\" # SPDX-License-Identifier: ISC
.Dd December 20, 2024
.Dt JALV.QT5 1
.Os
.Sh NAME
.Nm jalv.qt5
.Nd run an LV2 plugin with a Qt5 interface
.Sh SYNOPSIS
.Nm jalv.qt5
.Ar plugin_state
.Sh DESCRIPTION
.Nm
is a simple LV2 host that runs a single plugin.
This version has a Qt5 interface that shows either generic controls or a custom plugin GUI.
.Pp
.Nm
has one positional argument, which can be a plugin URI, preset URI, or the path to a bundle or data file that describes one.
.Pp
This version is mainly for testing and has no options or plugin selector.
For a more complete graphical version, see
.Xr jalv.gtk3 1 .
.Sh SEE ALSO
.Xr jalv 1 ,
.Xr jalv.gtk3 1 ,
.Xr lv2ls 1
.Sh AUTHORS
jalv was written by
.An David Robillard
.Aq Mt d@drobilla.net
with contributions by others.
Most of the Qt interface was added by Amadeus Folego and Timo Westkämper.
