.\" # Copyright 2024 David Robillard <d@drobilla.net>
.\" # SPDX-License-Identifier: ISC
.Dd December 20, 2024
.Dt JALV.QT6 1
.Os
.Sh NAME
.Nm jalv.qt6
.Nd run an LV2 plugin with a Qt6 interface
.Sh SYNOPSIS
.Nm jalv.qt6
.Ar plugin_uri
.Sh DESCRIPTION
.Nm
is a simple LV2 host that runs a single plugin.
This version has a Qt6 interface that shows either generic controls or a custom plugin GUI.
.Pp
This version has no options and requires the plugin URI to be given on the command line.
For a fully graphical version with a plugin selector, see
.Xr jalv.gtk3 1 .
.Sh SEE ALSO
.Xr jalv 1 ,
.Xr jalv.gtk3 1 ,
.Xr lv2ls 1
.Sh AUTHORS
jalv was written by
.An David Robillard
.Aq Mt d@drobilla.net
with contributions by others.
Most of the Qt interface was added by Amadeus Folego and Timo Westkämper.
