.\" # Copyright 2024-2025 David Robillard <d@drobilla.net>
.\" # SPDX-License-Identifier: ISC
.Dd August 1, 2025
.Dt JALV.GTK3 1
.Os
.Sh NAME
.Nm jalv.gtk3
.Nd run an LV2 plugin with a GTK3 interface
.Sh SYNOPSIS
.Nm jalv.gtk3
.Op Fl dghmpstx
.Op Fl b , Fl Fl buffer-size Ns = Ns Ar size
.Op Fl c , Fl Fl control Ns = Ns Ar setting
.Op Fl l , Fl Fl load Ns = Ns Ar dir
.Op Fl n , Fl Fl jack-name Ns = Ns Ar name
.Op Fl P , Fl Fl preset Ns = Ns Ar uri
.Op Fl r , Fl Fl update-frequency Ns = Ns Ar hz
.Op Fl S , Fl Fl scale-factor Ns = Ns Ar scale
.Op Fl U , Fl Fl ui-uri Ns = Ns Ar uri
.Ar plugin_uri
.Sh DESCRIPTION
.Nm
is a simple LV2 host that runs a single plugin.
This version has a GTK3 interface that shows either generic controls or a custom plugin GUI.
.Pp
The options are as follows:
.Bl -tag -width 3n
.It Fl b Ar size
Buffer size for plugin <=> UI communication.
.It Fl c Ar symbol=value
Set control value, for example,
.Fl c Ar vol=1.4
where
.Dq vol
is the symbol of some control port on the plugin.
.It Fl d
Dump plugin <=> UI communication.
.It Fl g
Show generic UI instead of custom plugin GUI.
.It Fl h
Print the command line options.
.It Fl l Ar dir
Load state from the given directory before running the plugin.
.It Fl m
Hide application menu, showing only the plugin interface.
.It Fl n Ar name
Use the given JACK client name.
Note that JACK may adjust the name if necessary unless
.Fl x
is also given.
.It Fl P uri
Load the given preset before running plugin.
.It Fl p
Print control output changes to
.Dv stdout .
.It Fl r Ar hz
Set the UI update frequency.
By default the screen refresh rate is used, typically 30 or 60 Hz.
.It Fl S Ar factor
Override the UI scale factor.
.It Fl s
Show controls that are normally hidden.
.It Fl t
Print debug trace messages.
This enables the
.Dq trace
LV2 log, which is used by some plugins to print debugging output.
Some extra internal error messages are also enabled.
Note that this may print in the audio thread, which can cause dropouts.
.It Fl U
URI Load the UI with the given URI.
.It Fl x
Use only the exact JACK client name given by
.Fl n
or exit if it's unavailable.
.El
.Sh COMMANDS
The Jalv prompt supports several commands for interactive control:
.Pp
.Bl -tag -width 16n -compact
.It Ic help
Display help message.
.It Ic controls
Print settable control values.
.It Ic monitors
Print output control values.
.It Ic presets
Print available presets.
.It Ic preset Ar uri
Set preset.
.It Ic set index value
Set control value by port index.
.It Ic set Ar symbol Ar value
Set control value by symbol.
.It Ar SYMBOL Cm = Ar VALUE
Set control value by symbol.
.El
.Sh SEE ALSO
.Xr jalv 1 ,
.Xr jalv.qt5 1
.Sh AUTHORS
jalv was written by
.An David Robillard
.Aq Mt d@drobilla.net
with contributions by others.
Most of the GTK interface was added by Alexandros Theodotou and Nick Lanham.
